#!/usr/bin/env bash
#  ██╗    ██╗ █████╗ ██╗     ██╗     ██████╗  █████╗ ██████╗ ███████╗██████╗
#  ██║    ██║██╔══██╗██║     ██║     ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
#  ██║ █╗ ██║███████║██║     ██║     ██████╔╝███████║██████╔╝█████╗  ██████╔╝
#  ██║███╗██║██╔══██║██║     ██║     ██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
#  ╚███╔███╔╝██║  ██║███████╗███████╗██║     ██║  ██║██║     ███████╗██║  ██║
#   ╚══╝╚══╝ ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝
#
#  ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#	gh0stzk - https://github.com/gh0stzk/dotfiles
#   obrn544 - https://github.com/obrn544/dotfiles
#	Info    - This script runs the rofi launcher, to select
#             the wallpapers included in the theme you are in.
#			  08.12.2023 08:37:20


# Verifies if x11-utils and imagemagick are installed
for app in x11-utils imagemagick; do
    if ! dpkg -l | grep -q "$app"; then
        notify-send "Missing package" "Please install the $app package to continue" --urgency=critical
        exit 1
    fi
done

# Set some variables
bspwm_dir="$HOME/.config/bspwm"
read -r current_rice < "$bspwm_dir"/.rice
wall_dir="$bspwm_dir/rices/$current_rice/walls"

# Trying to adapt the images and menu to your screen resolution.
monitor_res=$(($(xdpyinfo | awk '/dimensions/{print $2}' | cut -d 'x' -f1) * 15 / $(xdpyinfo | awk '/resolution/{print $2}' | cut -d 'x' -f1) * 2))
rofi_override="element-icon{size:${monitor_res}px;}"
rofi_command="rofi -dmenu -theme $bspwm_dir/src/rofi-themes/WallSelect.rasi -theme-str $rofi_override"

# Enable nullglob to avoid errors with empty globs
shopt -s nullglob

# Launch rofi with wallpaper selection and previsualization
wall_selection=$(
    for imagen in "$wall_dir"/*; do
        [[ $imagen == *.jpg || $imagen == *.jpeg || $imagen == *.png || $imagen == *.webp ]] || continue
        nombre_archivo=$(basename "$imagen")
        echo -e "$nombre_archivo\0icon\x1f$imagen"  # Usar la imagen original para la previsualización
    done | sort | $rofi_command -theme-str "$rofi_override"
)

# Set wallpaper if a valid option was selected
[[ -n "$wall_selection" ]] && feh --no-fehbg --bg-fill "${wall_dir}/${wall_selection}"